### ISSUE TITLE
Update README on Github? (palette = "tol.yl_or_br")

### ISSUE THREAD

**Issue by jlesg** [glottospace/glottospace#135]
Hi,

I was trying this package out and encountered an error while trying out this line from the REAME:

`glottomap(glottodata` = glottopols, color = "family_size_rank", palette = "tol.yl_or_br")

Then I noticed that "palette = ..." is not in the CRAN README, so it's probably not supposed to be there?

The error I had was "Error in glottocolpal(palette = palette) : object 'colpal' not found", btw.

Thanks, and all the best,

Jakob

**Comment by ruidongsmile** [comment]
Hi Jakob,
The most possible reason is that you are using tmap 3, we have updated glottospace to make it compatible with the latest version tmap 4.
So far tmap4 is not available from CRAN, but you can install tmap 4 from github, according to [https://github.com/r-tmap/tmap],  you can install it as follows:
`# install.packages("remotes")
install_github("r-tmap/tmaptools")
install_github("r-tmap/tmap")

# On Linux, with pak
# install.packages("pak")
pak::pak("r-tmap/tmap")

# Or from r-universe
install.packages("tmap", repos = c("https://r-tmap.r-universe.dev", "https://cloud.r-project.org"))`.
I hope this will be helpful to you.

Best,
Rui

**Comment by jlesg** [comment]
Thanks!
